#.interface: fill=lightblue
#.enumeration: fill=lightgreen
#.type: fill=lightgray

[Dashboard||]
[DashboardSidebar|+year: number;+isSidebarOpen: boolean;+isMobile: boolean;-router: Router;-destroyRef: DestroyRef|+ngOnInit(): void;+toggleSidebar(): void;-checkIfMobile(): void]
[OnInit]<:--[DashboardSidebar]
[FileDownload|-fileService: FileService;-route: ActivatedRoute;-router: Router;-formBuilder: FormBuilder;-cdr: ChangeDetectorRef;+fileDownloadForm: FormGroup<any>;+fileId: number;+fileToken: string;+file: FileInfo;+expMsgType: string;+expMsgIcon: string;+fileLink: string|-buildForm(): void;+ngOnInit(): void;+processFile(): void;+onDownload(): void;+downloadFile(): void]
[FileListing|-fileService: FileService;-authService: AuthService;-loadingService: LoadingService;-router: Router;-cdr: ChangeDetectorRef;+userFiles: FileInfo\[\];+filteredFiles: FileInfo\[\];+activeFilter: string;+isMobile: boolean;+message: string;+messageType: string;-messageTimeout: any;+menuOpen: number;+isLoading$: Observable<boolean>|+showMessage(): void;+ngOnInit(): void;+filterFiles(): void;+onDeleteFile(): void;+onViewFile(): void;+closeMessage(): void;+closeMenuWhenClickingOutside(): void;+toggleMenu(): void]
[OnInit]<:--[FileListing]
[FileUpload|-fileService: FileService;-authService: AuthService;-formBuilder: FormBuilder;-loadingService: LoadingService;+isLoading$: Observable<boolean>;+fileUploadForm: FormGroup<any>;+downloadLink: string;+dwlLinkMessage: string;+selectedFile: File;+fileIcon: string;+fileChecksum: string;+expirationOptions: Map<number, string>;+selectedExpiration: number;+currentUserEmail: string;+passwordMinLength: number;+getHumanReadableSize: (bytes: number, decimals?: number) => string|-buildForm(): void;+ngOnInit(): void;+calculateChecksum(): Promise<void>;+onFileSelected(): void;+resetSelectedFile(): void;+getFileFormData(): FormData;+onUpload(): Promise<void>;+copyLinkToClipboard(): void;+getDownloadURL(): string]
[OnInit]<:--[FileUpload]
[Header|-destroyRef: DestroyRef;-router: Router;+authService: AuthService;+currentRoute: string;+isMobile: boolean;+profileMenuOpen: boolean;+currentEmail$: Observable<string>;+isAuthenticated$: Observable<boolean>|+ngOnInit(): void;-updateCurrentRoute(): void;+logout(): void;+toggleProfileMenu(): void]
[OnInit]<:--[Header]
[Login|+loginForm: FormGroup<any>;-userService: UserService;-authService: AuthService;-destroyRef: DestroyRef;-router: Router;-formBuilder: FormBuilder|+onSubmit(): void]
[Register|+registerForm: FormGroup<any>;-userService: UserService;-destroyRef: DestroyRef;-router: Router;+passwordMinLength: number;-formBuilder: FormBuilder|+onSubmit(): void]