#.interface: fill=lightblue
#.enumeration: fill=lightgreen
#.type: fill=lightgray

[Register|+registerForm: FormGroup<any>;-userService: UserService;-destroyRef: DestroyRef;-router: Router;+passwordMinLength: number;-formBuilder: FormBuilder|+onSubmit(): void]