#.interface: fill=lightblue
#.enumeration: fill=lightgreen
#.type: fill=lightgray

[UserService|-httpClient: HttpClient|+register(): Observable<Object>;+login(): Observable<{ message: string; }>;+me(): Observable<AuthMeModel>]